# Generated by Django 5.1.4 on 2025-02-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestfileinfo",
            name="column_mapping",
            field=models.JSONField(
                blank=True,
                help_text="Mapping of input column names to schema column names",
                null=True,
                verbose_name="column mapping",
            ),
        ),
    ]
