# Generated by Django 5.1.4 on 2025-02-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_management", "0002_ingestfileinfo_column_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "column mapping",
                "verbose_name_plural": "column mappings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ObsColumnMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_column", models.CharField(max_length=255, verbose_name="input column")),
                ("schema_column", models.CharField(max_length=255, verbose_name="schema column")),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obs_mappings",
                        to="cell_management.columnmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "obs column mapping",
                "verbose_name_plural": "obs column mappings",
                "unique_together": {("mapping", "input_column"), ("mapping", "schema_column")},
            },
        ),
        migrations.CreateModel(
            name="VarColumnMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_column", models.CharField(max_length=255, verbose_name="input column")),
                ("schema_column", models.CharField(max_length=255, verbose_name="schema column")),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="var_mappings",
                        to="cell_management.columnmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "var column mapping",
                "verbose_name_plural": "var column mappings",
                "unique_together": {("mapping", "input_column"), ("mapping", "schema_column")},
            },
        ),
    ]
