# Generated by Django 5.1.4 on 2025-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_management", "0003_columnmapping_obscolumnmapping_varcolumnmapping"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cellfeatureinfo",
            name="cell_manage_origina_a821fb_idx",
        ),
        migrations.RenameField(
            model_name="cellfeatureinfo",
            old_name="feature_biotype",
            new_name="biotype",
        ),
        migrations.RenameField(
            model_name="cellfeatureinfo",
            old_name="feature_is_filtered",
            new_name="is_filtered",
        ),
        migrations.RenameField(
            model_name="cellfeatureinfo",
            old_name="feature_reference",
            new_name="reference",
        ),
        migrations.RemoveField(
            model_name="cellfeatureinfo",
            name="feature_name",
        ),
        migrations.RemoveField(
            model_name="cellfeatureinfo",
            name="original_id",
        ),
        migrations.AddField(
            model_name="cellfeatureinfo",
            name="ensemble_id",
            field=models.CharField(default="Asdasdas", max_length=256, unique=True, verbose_name="ensemble id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cellfeatureinfo",
            name="symbol",
            field=models.CharField(default="aa", max_length=255, verbose_name="symbol"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="cellfeatureinfo",
            index=models.Index(fields=["ensemble_id"], name="cell_manage_ensembl_7e55ba_idx"),
        ),
    ]
