# Generated by Django 5.1.4 on 2025-02-26 18:47

import nexus.backend.app_modules.cell_management.utils.column_mapping
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_management", "0004_remove_cellfeatureinfo_cell_manage_origina_a821fb_idx_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngestFileInfo",
            new_name="IngestInfo",
        ),
        migrations.AlterField(
            model_name="cellfeatureinfo",
            name="ensemble_id",
            field=models.CharField(max_length=256, verbose_name="ensemble id"),
        ),
        migrations.AlterField(
            model_name="obscolumnmapping",
            name="schema_column",
            field=models.CharField(
                choices=nexus.backend.app_modules.cell_management.utils.column_mapping.get_obs_column_choices,
                max_length=255,
                verbose_name="schema column",
            ),
        ),
        migrations.AlterField(
            model_name="varcolumnmapping",
            name="schema_column",
            field=models.CharField(
                choices=nexus.backend.app_modules.cell_management.utils.column_mapping.get_var_column_choices,
                max_length=255,
                verbose_name="schema column",
            ),
        ),
    ]
