repos:
  - repo: local
    hooks:
      - id: poe-lint
        name: poe lint
        entry: poetry run poe lint
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]