# Generated by Django 5.1.4 on 2025-03-21 14:17

import django.db.models.deletion
import nexus.backend.app_modules.curriculum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cell_count", models.IntegerField(verbose_name="cell count")),
                ("extract_bin_size", models.IntegerField(verbose_name="extract bin size")),
                ("extract_files_dir", models.CharField(max_length=512, verbose_name="extract files directory")),
                ("metadata_file_path", models.CharField(max_length=512, verbose_name="metadata file path")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "filters_json",
                    models.JSONField(
                        blank=True,
                        default=nexus.backend.app_modules.curriculum.models.default_empty_dict,
                        null=True,
                        verbose_name="filters json",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum",
                "verbose_name_plural": "curriculums",
            },
        ),
    ]
