# Generated by Django 5.1.4 on 2025-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_curriculum_extracted_bins"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="last_bin_number",
            field=models.IntegerField(default=1, verbose_name="last_bin_number"),
            preserve_default=False,
        ),
    ]
