# Generated by Django 5.1.4 on 2025-03-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_curriculum_last_bin_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculum",
            name="extracted_bins",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="last_bin_number",
        ),
    ]
