# Generated by Django 5.1.4 on 2025-04-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cell_management", "0001_initial"),
        ("ingest_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellfeatureinfo",
            name="ingest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="ingest_management.ingestinfo",
                verbose_name="ingest",
            ),
        ),
        migrations.AddField(
            model_name="cellinfo",
            name="ingest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="ingest_management.ingestinfo",
                verbose_name="ingest",
            ),
        ),
        migrations.AddField(
            model_name="featureschema",
            name="features",
            field=models.ManyToManyField(
                related_name="schemas", to="cell_management.featureinfo", verbose_name="features"
            ),
        ),
        migrations.AddIndex(
            model_name="cellfeatureinfo",
            index=models.Index(fields=["ensemble_id"], name="cell_manage_ensembl_7e55ba_idx"),
        ),
    ]
