# Generated by Django 5.1.4 on 2025-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cell_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellinfo",
            name="assay_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="assay ontology term id"
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="cell_type",
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name="cell type"),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="development_stage_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="development stage ontology term id"
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="disease_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="disease ontology term id"
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="organism_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="organism ontology term id"
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="original_id",
            field=models.CharField(max_length=256, verbose_name="original id"),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="self_reported_ethnicity_ontology_term_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=256,
                null=True,
                verbose_name="self-reported ethnicity ontology term id",
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="sex_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="sex ontology term id"
            ),
        ),
        migrations.AlterField(
            model_name="cellinfo",
            name="tissue_ontology_term_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name="tissue ontology term id"
            ),
        ),
    ]
