# Generated by Django 5.1.4 on 2026-01-30 00:00

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor) -> None:
    ingest_schema_model = apps.get_model("ingest_management", "IngestSchema")

    for ingest_schema in ingest_schema_model.objects.select_related("omics_dataset").order_by("id"):
        omics_dataset = ingest_schema.omics_dataset
        if omics_dataset and omics_dataset.schema_id is None:
            omics_dataset.schema_id = ingest_schema.id
            omics_dataset.save(update_fields=["schema"])


def backwards(apps, schema_editor) -> None:
    omics_dataset_model = apps.get_model("cell_management", "OmicsDataset")
    omics_dataset_model.objects.update(schema=None)


class Migration(migrations.Migration):
    dependencies = [
        ("cell_management", "0009_rename_bigquerydataset_to_omicsdataset"),
        ("ingest_management", "0008_rename_soma_ingest_schema_to_ingest_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="omicsdataset",
            name="schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="omics_datasets",
                to="ingest_management.ingestschema",
                verbose_name="ingest schema",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
