bindings:
- members:
  - projectEditor:dsp-cell-annotation-service
  - projectOwner:dsp-cell-annotation-service
  role: roles/storage.legacyBucketOwner
- members:
  - projectViewer:dsp-cell-annotation-service
  role: roles/storage.legacyBucketReader
- members:
  - projectEditor:dsp-cell-annotation-service
  - projectOwner:dsp-cell-annotation-service
  role: roles/storage.legacyObjectOwner
- members:
  - allUsers
  - projectViewer:dsp-cell-annotation-service
  role: roles/storage.objectViewer
