# Generated by Django 5.1.4 on 2025-09-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cell_management", "0006_remove_cellinfo_bigquery_dataset_and_more"),
        ("ingest_management", "0002_validationreport_validationreportitem"),
    ]

    operations = [
        # Clean existing IndexTracking rows to avoid NULL constraint issues during schema changes
        migrations.RunSQL(sql="DELETE FROM ingest_management_indextracking;"),
        migrations.AddField(
            model_name="indextracking",
            name="bigquery_dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingest_management_index_trackings",
                to="cell_management.bigquerydataset",
                verbose_name="BigQuery dataset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indextracking",
            name="resource_key",
            field=models.CharField(max_length=100, verbose_name="resource key"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="indextracking",
            unique_together={("bigquery_dataset", "resource_key")},
        ),
        migrations.RemoveField(
            model_name="indextracking",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="indextracking",
            name="table_object_id",
        ),
    ]
