# Generated by Django 5.1.4 on 2026-01-29 17:18

import django.db.models.deletion
from django.db import migrations, models

import cellarium.nexus.backend.ingest_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("cell_management", "0009_rename_bigquerydataset_to_omicsdataset"),
        ("ingest_management", "0004_rename_bigquery_dataset_to_omics_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomaIngestSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "x_validation_type",
                    models.CharField(
                        choices=[("count_matrix", "Count matrix"), ("feature_matrix", "Feature matrix")],
                        default="count_matrix",
                        max_length=32,
                        verbose_name="X validation type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "omics_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_management_soma_ingest_schemas",
                        to="cell_management.omicsdataset",
                        verbose_name="omics dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOMA ingest schema",
                "verbose_name_plural": "SOMA ingest schemas",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SomaVarSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "is_subset",
                    models.BooleanField(
                        default=True,
                        help_text="If true, input AnnData may contain a subset of features from the schema",
                        verbose_name="is subset",
                    ),
                ),
                ("var_parquet_file", models.FileField(upload_to="soma/var_schemas/", verbose_name="var parquet file")),
                (
                    "feature_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of features in the schema (derived from parquet index)",
                        verbose_name="feature count",
                    ),
                ),
                (
                    "var_columns",
                    models.JSONField(
                        default=cellarium.nexus.backend.ingest_management.models.default_empty_list,
                        help_text="List of var metadata columns stored in the parquet file",
                        verbose_name="var columns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "omics_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_management_soma_var_schemas",
                        to="cell_management.omicsdataset",
                        verbose_name="omics dataset",
                    ),
                ),
                (
                    "ingest_schema",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="var_schema",
                        to="ingest_management.somaingestschema",
                        verbose_name="ingest schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOMA var schema",
                "verbose_name_plural": "SOMA var schemas",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SomaObsColumnSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "dtype",
                    models.CharField(
                        choices=[
                            ("bool", "bool"),
                            ("int8", "int8"),
                            ("int16", "int16"),
                            ("int32", "int32"),
                            ("int64", "int64"),
                            ("float32", "float32"),
                            ("float64", "float64"),
                            ("string", "string"),
                            ("category", "category"),
                        ],
                        max_length=32,
                        verbose_name="dtype",
                    ),
                ),
                ("nullable", models.BooleanField(default=False, verbose_name="nullable")),
                (
                    "ingest_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obs_columns",
                        to="ingest_management.somaingestschema",
                        verbose_name="ingest schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOMA obs column schema",
                "verbose_name_plural": "SOMA obs column schemas",
                "unique_together": {("ingest_schema", "name")},
            },
        ),
    ]
