# Generated by Django 5.1.4 on 2026-01-30 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest_management", "0007_ingest_parent_and_file_fields"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SomaIngestSchema",
            new_name="IngestSchema",
        ),
    ]
