# Generated by Django 5.1.4 on 2026-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest_management", "0010_ingestschema_measurement_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingestinfo",
            options={"verbose_name": "ingest file", "verbose_name_plural": "ingest files"},
        ),
        migrations.AlterModelOptions(
            name="ingestschema",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "ingest schema",
                "verbose_name_plural": "ingest schemas",
            },
        ),
        migrations.AddField(
            model_name="validationreportitem",
            name="sanitized_file_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="sanitized file GCS path"),
        ),
    ]
