# Generated by Django 5.1.4 on 2026-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest_management", "0011_alter_ingestinfo_options_alter_ingestschema_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationreportitem",
            name="input_file_gcs_path",
        ),
        migrations.AddField(
            model_name="validationreportitem",
            name="input_file_path",
            field=models.CharField(default=1, max_length=1024, verbose_name="input file path"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="validationreportitem",
            name="sanitized_file_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="sanitized file path"),
        ),
    ]
