# Generated by Django 5.1.4 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest_management", "0012_remove_validationreportitem_input_file_gcs_path_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="somavarschema",
            old_name="is_subset",
            new_name="allow_subsets",
        ),
        migrations.AlterField(
            model_name="somavarschema",
            name="allow_subsets",
            field=models.BooleanField(
                default=True,
                help_text="If true, input AnnData may contain a subset of features from the schema",
                verbose_name="allow subsets",
            ),
        ),
    ]
