name: "Poetry Lint and Test"
description: "Run Poetry lint (poe lint) and tests (poe test) with a chosen Python version"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip
      working-directory: ${{ inputs.working-directory }}

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install poetry
        poetry --version
      working-directory: ${{ inputs.working-directory }}

    - name: Install Poetry plugins
      shell: bash
      run: |
        poetry self add poetry-plugin-export
        poetry self add "poetry-dynamic-versioning[plugin]"
      working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies (${{ inputs.with-groups }})
      shell: bash
      run: |
        poetry install --with ${{ inputs.with-groups }}
      working-directory: ${{ inputs.working-directory }}

    - name: Lint
      shell: bash
      run: poetry run poe lint
      working-directory: ${{ inputs.working-directory }}

    - name: Test
      shell: bash
      run: poetry run poe test
      working-directory: ${{ inputs.working-directory }}

inputs:
  python-version:
    description: "Python version to use (e.g., 3.10, 3.11, 3.12)"
    required: true
  with-groups:
    description: "Poetry dependency groups to install (comma-separated)"
    required: false
    default: "dev,test,backend"
  working-directory:
    description: "Working directory for running commands"
    required: false
    default: "."
