# Generated by Django 5.1.4 on 2025-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="extract_bin_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="extract bin count"),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="name",
            field=models.CharField(default="Name", max_length=512, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="curriculum",
            name="status",
            field=models.CharField(
                choices=[
                    ("PREPARE", "Prepare initiated..."),
                    ("EXTRACTING", "Extracting..."),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="PREPARE",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="cell_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="cell count"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="extract_bin_size",
            field=models.IntegerField(blank=True, null=True, verbose_name="extract bin size"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="extract_files_dir",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="extract files directory"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="metadata_file_path",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="metadata file path"),
        ),
    ]
