# Generated by Django 5.1.4 on 2025-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_curriculum_extract_bin_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculum",
            name="extract_files_dir",
        ),
        migrations.AddField(
            model_name="curriculum",
            name="extract_files_path",
            field=models.FilePathField(blank=True, null=True, verbose_name="extract files directory"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="metadata_file_path",
            field=models.FilePathField(blank=True, null=True, verbose_name="metadata file path"),
        ),
    ]
