# Generated by Django 5.1.4 on 2025-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_remove_curriculum_extract_files_dir_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="extract_files_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="extract files directory"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="metadata_file_path",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="metadata file path"),
        ),
    ]
