name: Nexus CI and Docker Build
on:
  push:
    branches: ['**']
    tags: ['*']
  workflow_dispatch:
    inputs:
      image-types:
        description: 'Image types to build. Can be `backend`, `workflows` or `both`. Default is `both`.'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - backend
          - workflows
      image-tag:
        description: 'Docker image tag. Will use the short hash of the last commit in the branch if nothing is passed in.'
        required: false
        default: ''
      add-latest-tag:
        description: 'Push a `latest` tag to the artifact registry.  Default is `true`.'
        required: false
        default: true
        type: boolean
      skip_tests:
        description: 'Skip Poetry lint and tests and only build Docker images.'
        required: false
        default: false
        type: boolean

jobs:

  validate:
    name: Validate (Poetry lint and tests)
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.skip_tests != true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Lint and test (Python ${{ matrix.python-version }})
        uses: ./.github/actions/poetry-check
        with:
          python-version: ${{ matrix.python-version }}
          with-groups: dev,test,backend

  update-docker-images:
    runs-on: ubuntu-latest
    needs: [validate]
    if: ${{ (github.event_name == 'workflow_dispatch' && (inputs.skip_tests == true || needs.validate.result == 'success')) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && needs.validate.result == 'success') }}

    permissions:
      contents: write
      id-token: write

    strategy:
      matrix:
        image-type: [ 'backend', 'workflows' ]

    env:
      DOCKER_REGISTRY_NAME: us-central1-docker.pkg.dev
      BACKEND_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nexus/nexus-backend
      WORKFLOWS_IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nexus/nexus-workflows
    steps:
      - uses: actions/checkout@v4

      - id: get-image-tag
        name: Get tag
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          elif [[ "${{ inputs.image-tag }}" == "" ]]; then
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ inputs.image-tag }}" >> $GITHUB_ENV
          fi
        shell: bash
      - id: build-backend
        uses: ./.github/actions/docker-build
        if: (github.event_name == 'workflow_dispatch' && matrix.image-type == 'backend' && (inputs.image-types == 'backend' || inputs.image-types == 'both')) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && matrix.image-type == 'backend')
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          image-name: ${{ env.BACKEND_IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}
          image-type: ${{ matrix.image-type }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          add-latest-tag: ${{ (github.event_name == 'workflow_dispatch' && inputs.add-latest-tag) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}

      - id: build-workflows
        uses: ./.github/actions/docker-build
        if: (github.event_name == 'workflow_dispatch' && matrix.image-type == 'workflows' && (inputs.image-types == 'workflows' || inputs.image-types == 'both')) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && matrix.image-type == 'workflows')
        with:
          docker-registry-name: ${{ env.DOCKER_REGISTRY_NAME }}
          image-name: ${{ env.WORKFLOWS_IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}
          image-type: ${{ matrix.image-type }}
          gcp-provider-id: ${{ secrets.GCP_PROVIDER_ID }}
          gcp-service-account-email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          add-latest-tag: ${{ (github.event_name == 'workflow_dispatch' && inputs.add-latest-tag) || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}
